/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeesalary;

/**
 * EmployeeSalaryApp.java
 * February 2025
 * @author Murilo Batiuk
 */
public class EmployeeSalaryGUI extends javax.swing.JFrame {

    /**
     * Creates new form PayrollGUI
     */
    public EmployeeSalaryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orangeLOGO = new javax.swing.JLabel();
        maintitleLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        returnBTN = new javax.swing.JButton();
        selectmonthCB = new javax.swing.JComboBox<>();
        selectmonthLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(235, 142, 39));

        orangeLOGO.setIcon(new javax.swing.ImageIcon("C:\\Users\\muril\\OneDrive\\Área de Trabalho\\College\\Semester 4\\Team Project - Julie Power\\My project\\Orange Logo.png")); // NOI18N

        maintitleLBL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        maintitleLBL.setText("ESTIMATED SALARY");

        titleLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titleLBL.setText("Hello, Employee!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maintitleLBL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orangeLOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orangeLOGO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(maintitleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLBL)
                        .addGap(21, 21, 21)))
                .addGap(72, 72, 72))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1513, 1513));

        returnBTN.setBackground(new java.awt.Color(235, 142, 39));
        returnBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        returnBTN.setForeground(new java.awt.Color(255, 255, 255));
        returnBTN.setText("return");

        selectmonthCB.setBackground(new java.awt.Color(235, 142, 39));
        selectmonthCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectmonthCB.setMaximumRowCount(12);
        selectmonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        selectmonthCB.setBorder(null);
        selectmonthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                january(evt);
                february(evt);
                march(evt);
                april(evt);
                may(evt);
                june(evt);
                july(evt);
                august(evt);
                september(evt);
                october(evt);
                november(evt);
                december(evt);
            }
        });

        selectmonthLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        selectmonthLBL.setText("select month:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(707, 707, 707)
                        .addComponent(returnBTN))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectmonthCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectmonthLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(734, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(selectmonthLBL)
                        .addGap(18, 18, 18)
                        .addComponent(selectmonthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 900, Short.MAX_VALUE)
                .addComponent(returnBTN)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, 1450, 1450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void january(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_january
        // TODO add your handling code here:
    }//GEN-LAST:event_january

    private void february(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_february
        // TODO add your handling code here:
    }//GEN-LAST:event_february

    private void march(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_march
        // TODO add your handling code here:
    }//GEN-LAST:event_march

    private void april(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_april
        // TODO add your handling code here:
    }//GEN-LAST:event_april

    private void may(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_may
        // TODO add your handling code here:
    }//GEN-LAST:event_may

    private void june(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_june
        // TODO add your handling code here:
    }//GEN-LAST:event_june

    private void july(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_july
        // TODO add your handling code here:
    }//GEN-LAST:event_july

    private void august(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_august
        // TODO add your handling code here:
        
    }//GEN-LAST:event_august

    private void september(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_september
        // TODO add your handling code here:
    }//GEN-LAST:event_september

    private void october(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_october
        // TODO add your handling code here:
    }//GEN-LAST:event_october

    private void november(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_november
        // TODO add your handling code here:
    }//GEN-LAST:event_november

    private void december(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_december
        // TODO add your handling code here:
    }//GEN-LAST:event_december

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSalaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maintitleLBL;
    private javax.swing.JLabel orangeLOGO;
    private javax.swing.JButton returnBTN;
    private javax.swing.JComboBox<String> selectmonthCB;
    private javax.swing.JLabel selectmonthLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
